name: Upload to S3

on:
  push:
    branches:
      - main  # Trigger only on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1  # Change region if necessary
    
    - name: Upload files to S3
      run: |
        aws s3 sync ./local-folder s3://your-bucket-name/ --delete
